#!/usr/bin/env bash
# Usage: jenv version-maven-read
set -e
[ -n "$JENV_DEBUG" ] && set -x

MAVEN_POM_FILE="pom.xml"

if [ -e "$MAVEN_POM_FILE" ]; then

  version="$(cat $MAVEN_POM_FILE | grep -Eo '<(java.version|maven.compiler.source|source)>(1\.[4-9]|[1-9]+)</.*>' | cut -f2 -d'>' | cut -f1 -d'<' | head -n1)"


  if [ -n "$version" ]; then
    echo "$version"
    exit
  fi
fi

exit 1
